import type { DungeonDefinition } from '@premium-rpg/shared-types';

// ─── DUNGEONS ────────────────────────────────────────────────────────
// One structured dungeon per region. Each is a linear sequence of authored
// encounters (trash packs, elites, miniboss, and a final boss) with
// unique modifiers and first-clear/repeat rewards. NOT enemy-selection.

export const DARKWOOD_CAVERNS: DungeonDefinition = {
  id: 'darkwood-caverns',
  name: 'Darkwood Caverns',
  regionId: 'darkwood-forest',
  description:
    'A winding system of moonlit caverns beneath the Darkwood Forest, home to the vampire Count Vlad and his undead spawn.',
  recommendedLevel: 10,
  maxFloor: 5,
  entryRequirement: {
    level: 8,
    keyId: 'cavern_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 8 }],
  },
  encounters: [
    {
      id: 'caverns-1',
      type: 'trash',
      name: 'Cave Bat Swarm',
      description: 'A chittering mass of blood-hungry cave bats.',
      enemyIds: ['cave_bat', 'cave_bat', 'cave_bat'],
      modifiers: ['quick'],
      xpReward: 60,
      goldReward: 20,
    },
    {
      id: 'caverns-2',
      type: 'elite',
      name: 'Darkwood Web',
      description: 'A spider matron guarding the passage with webbed traps.',
      enemyId: 'darkwood_spider',
      modifiers: ['tanky', 'cursed'],
      xpReward: 90,
      goldReward: 30,
    },
    {
      id: 'caverns-3',
      type: 'trash',
      name: 'Risen Corpses',
      description: 'Shambling undead risen by the count\'s dark aura.',
      enemyIds: ['zombie', 'ghoul', 'zombie'],
      modifiers: ['regenerating'],
      xpReward: 85,
      goldReward: 28,
    },
    {
      id: 'caverns-4',
      type: 'miniboss',
      name: 'The Werewolf Sentinel',
      description: 'A lycanthrope guardian that once protected the forest.',
      enemyId: 'werewolf',
      modifiers: ['offensive', 'quick'],
      xpReward: 130,
      goldReward: 45,
      guaranteedDrops: [{ itemId: 'werewolf_claw', quantity: 1 }],
    },
    {
      id: 'caverns-boss',
      type: 'boss',
      name: 'Count Vlad',
      description: 'The ancient vampire lord who rules the caverns.',
      enemyId: 'count_vlad',
      modifiers: ['offensive', 'regenerating'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'darkwood_log', quantity: 3 }],
    weightedLootTableId: 'dungeon_darkwood',
    xp: 400,
    gold: 150,
    firstClearBonus: [{ itemId: 'vampire_fang', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const CRUMBLING_CITADEL: DungeonDefinition = {
  id: 'crumbling-citadel',
  name: 'Crumbling Citadel',
  regionId: 'ruined-province',
  description:
    'The shattered stronghold of a fallen kingdom, now crawling with the undead legions of the Ancient Lich.',
  recommendedLevel: 20,
  maxFloor: 6,
  entryRequirement: {
    level: 18,
    keyId: 'citadel_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 18 }],
  },
  encounters: [
    {
      id: 'citadel-1',
      type: 'trash',
      name: 'Undead Garrison',
      description: 'Rank upon rank of skeletal soldiers reassembling endlessly.',
      enemyIds: ['skeleton_knight', 'skeleton_knight', 'grave_guardian'],
      modifiers: ['defensive'],
      xpReward: 140,
      goldReward: 45,
    },
    {
      id: 'citadel-2',
      type: 'elite',
      name: 'Corrupted Gatekeeper',
      description: 'A mage whose arcane power was corrupted by the lich.',
      enemyId: 'corrupted_mage',
      modifiers: ['offensive', 'quick'],
      xpReward: 180,
      goldReward: 55,
    },
    {
      id: 'citadel-3',
      type: 'trash',
      name: 'The Wall of Souls',
      description: 'Soul-wracked guardians bound to the citadel walls.',
      enemyIds: ['wraith', 'soul_reaper', 'wraith'],
      modifiers: ['cursed', 'regenerating'],
      xpReward: 200,
      goldReward: 60,
    },
    {
      id: 'citadel-4',
      type: 'miniboss',
      name: 'Stone Golem',
      description: 'A colossal construct animated to crush all intruders.',
      enemyId: 'stone_golem',
      modifiers: ['tanky', 'defensive'],
      xpReward: 260,
      goldReward: 80,
    },
    {
      id: 'citadel-5',
      type: 'elite',
      name: 'The Soul Reaper',
      description: 'A dread executioner who harvests the souls of the damned.',
      enemyId: 'soul_reaper',
      modifiers: ['offensive', 'cursed'],
      xpReward: 300,
      goldReward: 90,
    },
    {
      id: 'citadel-boss',
      type: 'boss',
      name: 'The Ancient Lich',
      description: 'The necromancer king who rules the ruined province.',
      enemyId: 'ancient_lich',
      modifiers: ['offensive', 'regenerating'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'runite_bar', quantity: 1 }],
    weightedLootTableId: 'dungeon_citadel',
    xp: 650,
    gold: 220,
    firstClearBonus: [{ itemId: 'lich_philactery', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const FROZEN_SUMMIT: DungeonDefinition = {
  id: 'frozen-summit',
  name: 'The Frozen Summit',
  regionId: 'mountain-stronghold',
  description:
    'The glacially-forged peak of the mountain stronghold, crowned by the Frost Giant King and his elemental court.',
  recommendedLevel: 32,
  maxFloor: 6,
  entryRequirement: {
    level: 30,
    keyId: 'summit_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 30 }],
  },
  encounters: [
    {
      id: 'summit-1',
      type: 'trash',
      name: 'Glacial Patrol',
      description: 'Frost-forged warriors patrolling the frozen passes.',
      enemyIds: ['mountain_troll', 'ice_elemental', 'mountain_troll'],
      modifiers: ['defensive'],
      xpReward: 260,
      goldReward: 85,
    },
    {
      id: 'summit-2',
      type: 'elite',
      name: 'Wyvern Aerie',
      description: 'Frost drakes nesting in the icy cliffs.',
      enemyId: 'frost_drake',
      modifiers: ['quick', 'offensive'],
      xpReward: 320,
      goldReward: 100,
    },
    {
      id: 'summit-3',
      type: 'trash',
      name: 'Runite Legion',
      description: 'Elite runite-armored warriors of the stronghold.',
      enemyIds: ['giant_warrior', 'runite_elemental', 'giant_warrior'],
      modifiers: ['defensive', 'tanky'],
      xpReward: 360,
      goldReward: 115,
    },
    {
      id: 'summit-4',
      type: 'miniboss',
      name: 'Frost Wyrm',
      description: 'An ancient ice wyrm guarding the summit approach.',
      enemyId: 'wyvern',
      modifiers: ['regenerating', 'offensive'],
      xpReward: 420,
      goldReward: 135,
    },
    {
      id: 'summit-5',
      type: 'elite',
      name: 'The Mountain King',
      description: 'A titan of stone and ice who commands the summit\'s defense.',
      enemyId: 'mountain_king',
      modifiers: ['tanky', 'defensive'],
      xpReward: 480,
      goldReward: 155,
    },
    {
      id: 'summit-boss',
      type: 'boss',
      name: 'The Frost Giant King',
      description: 'The sovereign of frost who rules the eternal winter of the summit.',
      enemyId: 'frost_giant_king',
      modifiers: ['offensive', 'regenerating', 'quick'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'mountain_crystal', quantity: 2 }],
    weightedLootTableId: 'dungeon_summit',
    xp: 900,
    gold: 300,
    firstClearBonus: [{ itemId: 'frost_crown', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const SUNKEN_CATACOMBS: DungeonDefinition = {
  id: 'sunken-catacombs',
  name: 'The Sunken Catacombs',
  regionId: 'haunted-marsh',
  description:
    'The flooded burial city beneath the Haunted Marsh, home to the Tyrant of the Deep and its lingering horrors.',
  recommendedLevel: 57,
  maxFloor: 7,
  entryRequirement: {
    level: 55,
    keyId: 'sunken_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 55 }],
  },
  encounters: [
    {
      id: 'sunken-1',
      type: 'trash',
      name: 'Plague Nest',
      description: 'A swarming nest of plague-riddled vermin.',
      enemyIds: ['plague_rat', 'plague_rat', 'bog_horror'],
      modifiers: ['quick', 'cursed'],
      xpReward: 480,
      goldReward: 160,
    },
    {
      id: 'sunken-2',
      type: 'elite',
      name: 'The Marsh Wraith',
      description: 'A lingering specter that haunts the flooded halls.',
      enemyId: 'marsh_wraith',
      modifiers: ['offensive', 'quick'],
      xpReward: 540,
      goldReward: 175,
    },
    {
      id: 'sunken-3',
      type: 'trash',
      name: 'Troll Deluge',
      description: 'Swamp trolls wading through the rising waters.',
      enemyIds: ['swamp_troll', 'bog_horror', 'swamp_troll'],
      modifiers: ['tanky', 'regenerating'],
      xpReward: 560,
      goldReward: 185,
    },
    {
      id: 'sunken-4',
      type: 'elite',
      name: 'The Spectral Knights',
      description: 'Undead knights holding vigil over the catacomb gates.',
      enemyId: 'spectral_knight',
      modifiers: ['defensive', 'offensive'],
      xpReward: 600,
      goldReward: 195,
    },
    {
      id: 'sunken-5',
      type: 'miniboss',
      name: 'The Flood Lich',
      description: 'An ancient undead sorcerer commanding the catacomb waters.',
      enemyId: 'flood_lich',
      modifiers: ['offensive', 'regenerating', 'cursed'],
      xpReward: 680,
      goldReward: 220,
    },
    {
      id: 'sunken-6',
      type: 'elite',
      name: 'The Marsh Serpent',
      description: 'A colossal serpent coiled in the deepest pool.',
      enemyId: 'marsh_serpent',
      modifiers: ['tanky', 'offensive'],
      xpReward: 640,
      goldReward: 210,
    },
    {
      id: 'sunken-boss',
      type: 'boss',
      name: 'The Tyrant of the Deep',
      description: 'The drowned sovereign whose domain is the flooded abyss.',
      enemyId: 'tyrant_of_the_deep',
      modifiers: ['offensive', 'regenerating', 'tanky'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'serpent_fang', quantity: 2 }],
    weightedLootTableId: 'dungeon_sunken',
    xp: 1200,
    gold: 400,
    firstClearBonus: [{ itemId: 'tidal_crown', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const CITADEL_DEPTHS: DungeonDefinition = {
  id: 'citadel-depths',
  name: 'The Citadel Depths',
  regionId: 'forgotten-citadel',
  description:
    'The sunless depths beneath the Forgotten Citadel, where the Arch Demon holds court over a legion of horrors.',
  recommendedLevel: 72,
  maxFloor: 7,
  entryRequirement: {
    level: 70,
    keyId: 'depth_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 70 }],
  },
  encounters: [
    {
      id: 'depths-1',
      type: 'trash',
      name: 'Guardian Phalanx',
      description: 'Obsidian-forged guardians forming an unbreakable wall.',
      enemyIds: ['citadel_guardian', 'obsidian_golem', 'citadel_guardian'],
      modifiers: ['defensive', 'tanky'],
      xpReward: 820,
      goldReward: 280,
    },
    {
      id: 'depths-2',
      type: 'elite',
      name: 'The Wailing Herald',
      description: 'A banshee that announces the approach of doom.',
      enemyId: 'wailing_herald',
      modifiers: ['cursed', 'quick'],
      xpReward: 880,
      goldReward: 300,
    },
    {
      id: 'depths-3',
      type: 'trash',
      name: 'Fallen Legion',
      description: 'Corrupted paladins and obsidian colossi marching in unison.',
      enemyIds: ['fallen_pally', 'obsidian_golem', 'fallen_pally'],
      modifiers: ['offensive', 'regenerating'],
      xpReward: 900,
      goldReward: 310,
    },
    {
      id: 'depths-4',
      type: 'elite',
      name: 'The Void Stalker',
      description: 'A dimensional predator hunting in the depths.',
      enemyId: 'void_stalker',
      modifiers: ['quick', 'offensive'],
      xpReward: 960,
      goldReward: 330,
    },
    {
      id: 'depths-5',
      type: 'miniboss',
      name: 'The Hollow King',
      description: 'The undead sovereign of the forgotten citadel.',
      enemyId: 'hollow_king',
      modifiers: ['offensive', 'regenerating', 'cursed'],
      xpReward: 1050,
      goldReward: 360,
    },
    {
      id: 'depths-6',
      type: 'elite',
      name: 'Obsidian Vanguard',
      description: 'The final line of construct defenders before the throne.',
      enemyIds: ['obsidian_golem', 'citadel_guardian', 'obsidian_golem'],
      modifiers: ['tanky', 'defensive'],
      xpReward: 1000,
      goldReward: 350,
    },
    {
      id: 'depths-boss',
      type: 'boss',
      name: 'The Arch Demon',
      description: 'The conqueror of the citadel and lord of the depths.',
      enemyId: 'arch_demon',
      modifiers: ['offensive', 'regenerating', 'quick'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'obsidian_shard', quantity: 3 }],
    weightedLootTableId: 'dungeon_depths',
    xp: 1600,
    gold: 600,
    firstClearBonus: [{ itemId: 'demon_horn', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const MOLTEN_CORE: DungeonDefinition = {
  id: 'molten-core',
  name: 'The Molten Core',
  regionId: 'volcanic-wasteland',
  description:
    'The burning heart of the volcanic wasteland, where the Magma Tyrant shapes the earth with eruptive fury.',
  recommendedLevel: 87,
  maxFloor: 6,
  entryRequirement: {
    level: 85,
    keyId: 'core_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 85 }],
  },
  encounters: [
    {
      id: 'core-1',
      type: 'trash',
      name: 'Magma Hatch',
      description: 'Young magma drakes emerging from the molten pools.',
      enemyIds: ['magma_drake', 'magma_drake', 'infernal_elemental'],
      modifiers: ['offensive', 'quick'],
      xpReward: 1100,
      goldReward: 420,
    },
    {
      id: 'core-2',
      type: 'elite',
      name: 'The Infernal Elemental',
      description: 'A living storm of flame and fury.',
      enemyId: 'infernal_elemental',
      modifiers: ['regenerating', 'offensive'],
      xpReward: 1180,
      goldReward: 450,
    },
    {
      id: 'core-3',
      type: 'trash',
      name: 'Fire Giant Cohort',
      description: 'An advancing column of volcanic titans.',
      enemyIds: ['fire_giant', 'fire_giant', 'ash_wraith'],
      modifiers: ['tanky', 'defensive'],
      xpReward: 1200,
      goldReward: 460,
    },
    {
      id: 'core-4',
      type: 'miniboss',
      name: 'The Ash Wraith',
      description: 'The spectral remnant of a pyroclasm-swallowed mage.',
      enemyId: 'ash_wraith',
      modifiers: ['cursed', 'quick'],
      xpReward: 1280,
      goldReward: 490,
    },
    {
      id: 'core-5',
      type: 'elite',
      name: 'The Ember Serpent',
      description: 'A lava-swimming wyrm coiled at the core\'s threshold.',
      enemyId: 'ember_serpent',
      modifiers: ['quick', 'offensive', 'tanky'],
      xpReward: 1320,
      goldReward: 505,
    },
    {
      id: 'core-boss',
      type: 'boss',
      name: 'The Magma Tyrant',
      description: 'The living will of the volcano itself.',
      enemyId: 'magma_tyrant',
      modifiers: ['offensive', 'regenerating', 'tanky', 'quick'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'ember_crystal', quantity: 3 }],
    weightedLootTableId: 'dungeon_core',
    xp: 1900,
    gold: 750,
    firstClearBonus: [{ itemId: 'infernal_core', quantity: 1 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.5,
};

export const ABYSSAL_THRONE: DungeonDefinition = {
  id: 'abyssal-throne',
  name: 'The Abyssal Throne',
  regionId: 'ancient-endgame',
  description:
    'The seat of the Unmaker at the very end of reality. Only the mightiest champions can tread these broken halls.',
  recommendedLevel: 97,
  maxFloor: 6,
  entryRequirement: {
    level: 95,
    keyId: 'abyss_key',
    keyConsumedOnEntry: true,
    unlockConditions: [{ type: 'level', target: 'level', comparison: 'gte', value: 95 }],
  },
  encounters: [
    {
      id: 'abyss-1',
      type: 'trash',
      name: 'Void Vanguard',
      description: 'Abyssal walkers straddling the rifts of reality.',
      enemyIds: ['abyssal_walker', 'abyssal_walker', 'time_reaver'],
      modifiers: ['cursed', 'quick'],
      xpReward: 1600,
      goldReward: 700,
    },
    {
      id: 'abyss-2',
      type: 'elite',
      name: 'The Time Reaver',
      description: 'A chronal devourer that unravels moments.',
      enemyId: 'time_reaver',
      modifiers: ['quick', 'offensive'],
      xpReward: 1700,
      goldReward: 740,
    },
    {
      id: 'abyss-3',
      type: 'elite',
      name: 'The Void Lord',
      description: 'The sovereign of the void and herald of the Unmaker.',
      enemyId: 'void_lord',
      modifiers: ['offensive', 'regenerating', 'cursed'],
      xpReward: 1800,
      goldReward: 780,
    },
    {
      id: 'abyss-4',
      type: 'trash',
      name: 'Elder Brood',
      description: 'Fragment of the elder dragons\' eternal wrath.',
      enemyIds: ['abyssal_walker', 'elder_dragon', 'abyssal_walker'],
      modifiers: ['tanky', 'defensive'],
      xpReward: 1750,
      goldReward: 760,
    },
    {
      id: 'abyss-5',
      type: 'miniboss',
      name: 'The Elder Dragon',
      description: 'The primordial wyrm that stands eternal before the throne.',
      enemyId: 'elder_dragon',
      modifiers: ['offensive', 'regenerating', 'tanky'],
      xpReward: 1950,
      goldReward: 850,
    },
    {
      id: 'abyss-boss',
      type: 'boss',
      name: 'The Unmaker',
      description: 'The final evil whose purpose is to unmake all of existence.',
      enemyId: 'the_unmaker',
      modifiers: ['offensive', 'regenerating', 'tanky', 'quick', 'cursed'],
    },
  ],
  reward: {
    guaranteed: [{ itemId: 'void_crystal', quantity: 4 }],
    weightedLootTableId: 'dungeon_abyss',
    xp: 2400,
    gold: 1000,
    firstClearBonus: [{ itemId: 'abyssal_shard', quantity: 3 }],
  },
  repeatable: true,
  repeatRewardMultiplier: 0.4,
};

// ─── DUNGEON REGISTRY ────────────────────────────────────────────────

export const DUNGEONS: Record<string, DungeonDefinition> = {
  [DARKWOOD_CAVERNS.id]: DARKWOOD_CAVERNS,
  [CRUMBLING_CITADEL.id]: CRUMBLING_CITADEL,
  [FROZEN_SUMMIT.id]: FROZEN_SUMMIT,
  [SUNKEN_CATACOMBS.id]: SUNKEN_CATACOMBS,
  [CITADEL_DEPTHS.id]: CITADEL_DEPTHS,
  [MOLTEN_CORE.id]: MOLTEN_CORE,
  [ABYSSAL_THRONE.id]: ABYSSAL_THRONE,
};

export const ALL_DUNGEONS: DungeonDefinition[] = [
  DARKWOOD_CAVERNS,
  CRUMBLING_CITADEL,
  FROZEN_SUMMIT,
  SUNKEN_CATACOMBS,
  CITADEL_DEPTHS,
  MOLTEN_CORE,
  ABYSSAL_THRONE,
];

// Dungeon base keys (consumed on entry when keyId present)
export const DUNGEON_KEYS: Record<string, { itemId: string; dungeonId: string }> = {
  cavern_key: { itemId: 'cavern_key', dungeonId: DARKWOOD_CAVERNS.id },
  citadel_key: { itemId: 'citadel_key', dungeonId: CRUMBLING_CITADEL.id },
  summit_key: { itemId: 'summit_key', dungeonId: FROZEN_SUMMIT.id },
  sunken_key: { itemId: 'sunken_key', dungeonId: SUNKEN_CATACOMBS.id },
  depth_key: { itemId: 'depth_key', dungeonId: CITADEL_DEPTHS.id },
  core_key: { itemId: 'core_key', dungeonId: MOLTEN_CORE.id },
  abyss_key: { itemId: 'abyss_key', dungeonId: ABYSSAL_THRONE.id },
};
